# Database Configuration
DB_HOST: localhost
DB_USER: postgres
DB_PASSWORD: password
DB_NAME: nms
DB_PORT: 5432

# Server Configuration
SERVER_ADDRESS: ":8080"
PLUGINS_DIR: "plugins"

# Availability Check Configuration
POLL_INTERVAL_SEC: 5
AV_CHECK_TIMEOUT_MS: 500
AV_CHECK_RETRIES: 2

# Worker Configuration
POLL_WORKER_COUNT: 10
DISC_WORKER_COUNT: 5

# Authentication
SESSION_DURATION_HOURS: 168

# Metrics Query Defaults
METRICS_DEFAULT_LIMIT: 100
METRICS_DEFAULT_LOOKBACK_HOURS: 1
