[package]
name = "winrm-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "winrm"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
winrm-rs = "1.1"
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
